In [214]:
from pathlib import Path
import pandas as pd
import  gc 
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
import catboost
import lightgbm as lgb
from catboost import datasets, CatBoostRegressor

In [215]:
p = Path.home() / 'AppData' / 'Local' / 'Packages' / \
...     'PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0' / \
...     'LocalCache' / 'local-packages' / 'Python39' / 'Scripts' / 'sample_train_numerai.csv'

train = pd.read_csv(p)

In [216]:
y=train["target"]
X=train.drop("target",axis=1)
X

,era,data_type,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,1,train,3,4,0,3,3,1,1,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,1,train,4,2,4,4,0,0,4,4,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,1,train,2,4,0,3,0,3,2,4,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,1,train,2,1,3,0,3,0,3,3,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,1,train,4,1,4,1,0,4,0,4,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,train,0,1,4,0,3,2,3,2,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,1,train,2,3,3,0,3,0,1,0,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,1,train,3,1,1,0,0,1,0,3,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,1,train,2,0,2,1,4,1,2,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,1,train,3,4,2,2,0,4,3,4,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [217]:
X=X.drop("era",axis=1)
X=X.drop("data_type",axis=1)
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,3,4,0,3,3,1,1,0,0,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,4,2,4,4,0,0,4,4,3,0,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,2,4,0,3,0,3,2,4,2,2,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,2,1,3,0,3,0,3,3,4,2,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,4,1,4,1,0,4,0,4,4,0,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,2,3,3,0,3,0,1,0,2,3,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,3,1,1,0,0,1,0,3,1,2,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,2,0,2,1,4,1,2,2,1,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,3,4,2,2,0,4,3,4,2,3,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [218]:
good_cols=[col for col in X.columns if not col.startswith("target")]
 
X=X[good_cols]
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_sprucer_godlier_assembling,feature_venturesome_jesting_characterisation,feature_unstained_anhedonic_hetty,feature_vivisectional_latvian_dispensator,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,2,2,2,2
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,2,2,2,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,2,2,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,2,2,2,2
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,2,2,2,2,2,2,2,2,2,2
96,2,3,3,0,3,0,1,0,2,3,...,2,2,2,2,2,2,2,2,2,2
97,3,1,1,0,0,1,0,3,1,2,...,2,2,2,2,2,2,2,2,2,2
98,2,0,2,1,4,1,2,2,1,2,...,2,2,2,2,2,2,2,2,2,2
99,3,4,2,2,0,4,3,4,2,3,...,2,2,2,2,2,2,2,2,2,2

In [219]:
X=X.reset_index(drop=True)
y=y.reset_index(drop=True)

In [220]:
X.isnull().values.any()

np.False_

In [221]:
def  kin_energy(x):
    f=np.unique(x,return_counts=True)
    prob=f[1]/x.shape[0]
    energy=np.sum(prob**2)
    return  energy

In [222]:
def count_common(x):
    a=np.array(x)
    b=np.where(a==np.min(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [223]:
def count_least(x):
    a=np.array(x)
    b=np.where(a==np.max(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [224]:
X["KINETIC_FEAT"]=X.apply(kin_energy,axis=1)
X["mean_FEAT"]=X[good_cols].apply(np.mean,axis=1)
X["COMMON_COUNT_FEAT"]=X.apply(count_common,axis=1)
X["LEAST_COUNT_FEAT"]=X.apply(count_least,axis=1)

In [225]:
del train
gc.collect()

0

In [226]:
X["KINETIC_FEAT"]=np.round(X["KINETIC_FEAT"], decimals=2)
X["mean_FEAT"]=np.round(X["mean_FEAT"], decimals=2)

In [227]:
X["KINETIC_FEAT"]=( X["KINETIC_FEAT"]% 1 * 100).astype(int)
X["mean_FEAT"]=( X["mean_FEAT"]% 1 * 100).astype(int)

In [228]:
train=X

In [229]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,40,0,182,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,39,95,400,1
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,43,96,167,1
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,40,0,203,1
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,38,2,221,1

In [230]:
np.corrcoef(X["feature_elusive_vapoury_accomplice"], X["feature_approbatory_labroid_coracle"])

array([[ 1.        , -0.06994773],
       [-0.06994773,  1.        ]])

In [231]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [232]:
def gcd(a, b):
    if a == 0 or b == 0:
        return max(a, b)
    return gcd(b, a % b)

In [233]:
X["GCD_FEAT"]=X.apply(lambda r: gcd(r["feature_elusive_vapoury_accomplice"],r["feature_fortified_repressed_baird"]),axis=1)

In [234]:
def l(a, b):
    if a==0 or b==0:
        return max(a, b)
    else:
        if a!=0 and b!=0:
           lcm=(a*b)/gcd(a, b)
    if a==0 and b==0:
        return 0
    return lcm

In [235]:
X["LCM_FEAT"]=X.apply(lambda r: l(r["feature_elusive_vapoury_accomplice"], r["feature_limiest_heliolithic_york"]),axis=1)

In [236]:
X["LCM_FEAT"]=X["LCM_FEAT"].astype(int)

In [237]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,40,0,182,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,39,95,400,1,4,4
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,43,96,167,1,3,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,40,0,203,1,1,6
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,38,2,221,1,1,2

In [238]:
def sum_q(l, r, x):
   
    a=np.array(x)
    n=len(a)
    if l>r:
        aux=l
        l=r
        r=aux
        s=sum(a[i] for i in range(l, r))
        return s   
    if r==l:
        return a[r]
    if n>=r and  n>l:
            s=sum(a[i] for i in range(l, r))
  
            return s

In [239]:
x=[1, -1, 7, 2, -3, -2, 4]
print (sum_q(4, 4, x))
print (sum_q(2, 6, x))

-3
4

In [240]:
np.corrcoef(X["feature_busy_clear_divi"],X["feature_pococurante_typological_crump"])

C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

array([[ 1., nan],
       [nan, nan]])

In [241]:
X["GCD1_FEAT"]=X.apply(lambda r: gcd(r["feature_busy_clear_divi"],r["feature_pococurante_typological_crump"]),axis=1)

In [242]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,40,0,182,1,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,39,95,400,1,4,4,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,43,96,167,1,3,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,40,0,203,1,1,6,1
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,38,2,221,1,1,2,2

In [243]:
np.corrcoef(X["feature_glandered_unimproved_peafowl"],X["feature_starving_unwet_transubstantiationalist"])

array([[1.      , 0.267411],
       [0.267411, 1.      ]])

In [244]:
X["LCM1_FEAT"]=X.apply(lambda r: l(r["feature_glandered_unimproved_peafowl"], r["feature_starving_unwet_transubstantiationalist"]),axis=1)

In [245]:
X["LCM1_FEAT"]=X["LCM_FEAT"].astype(int)

In [246]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,40,0,182,1,1,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,39,95,400,1,4,4,2,4
2,2,4,0,3,0,3,2,4,2,2,...,2,2,43,96,167,1,3,2,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,40,0,203,1,1,6,1,6
4,4,1,4,1,0,4,0,4,4,0,...,2,2,38,2,221,1,1,2,2,2

In [247]:
X["SUM_QUERY1_FEAT"]=X.apply(lambda r: sum_q(r["GCD1_FEAT"], r["LCM1_FEAT"], r),axis=1)

In [248]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,40,0,182,1,1,1,1,1,4
1,4,2,4,4,0,0,4,4,3,0,...,2,39,95,400,1,4,4,2,4,8
2,2,4,0,3,0,3,2,4,2,2,...,2,43,96,167,1,3,2,2,2,0
3,2,1,3,0,3,0,3,3,4,2,...,2,40,0,203,1,1,6,1,6,7
4,4,1,4,1,0,4,0,4,4,0,...,2,38,2,221,1,1,2,2,2,4

In [249]:
X["SUM_QUERY_FEAT"]=X.apply(lambda r: sum_q(r["GCD_FEAT"], r["LCM_FEAT"], r),axis=1)

In [250]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,40,0,182,1,1,1,1,1,4,4
1,4,2,4,4,0,0,4,4,3,0,...,39,95,400,1,4,4,2,4,8,0
2,2,4,0,3,0,3,2,4,2,2,...,43,96,167,1,3,2,2,2,0,0
3,2,1,3,0,3,0,3,3,4,2,...,40,0,203,1,1,6,1,6,7,7
4,4,1,4,1,0,4,0,4,4,0,...,38,2,221,1,1,2,2,2,4,1

In [251]:
def josephus(n, k):
   
    if n==1: 
        return 0
    else:
        
        return  (josephus(n - 1, k) + k) % n

In [252]:
X["JOSE_FEAT"]=X.apply(lambda r: josephus(100, r["GCD_FEAT"]),axis=1)

In [253]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,0,182,1,1,1,1,1,4,4,99
1,4,2,4,4,0,0,4,4,3,0,...,95,400,1,4,4,2,4,8,0,33
2,2,4,0,3,0,3,2,4,2,2,...,96,167,1,3,2,2,2,0,0,90
3,2,1,3,0,3,0,3,3,4,2,...,0,203,1,1,6,1,6,7,7,99
4,4,1,4,1,0,4,0,4,4,0,...,2,221,1,1,2,2,2,4,1,99

In [254]:
X["JOSE1_FEAT"]=X.apply(lambda r: josephus(100, r["GCD1_FEAT"]),axis=1)

In [255]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,182,1,1,1,1,1,4,4,99,99
1,4,2,4,4,0,0,4,4,3,0,...,400,1,4,4,2,4,8,0,33,72
2,2,4,0,3,0,3,2,4,2,2,...,167,1,3,2,2,2,0,0,90,72
3,2,1,3,0,3,0,3,3,4,2,...,203,1,1,6,1,6,7,7,99,99
4,4,1,4,1,0,4,0,4,4,0,...,221,1,1,2,2,2,4,1,99,72

In [256]:
def money(x):
    a=0
    while x>0:
        if x>=10:
            x=x-10
        else: 
            if x>=5:
                x=x-5
            else:
                x=x-1
            a=a+1
    return a

In [257]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [258]:
params = {
        "n_estimators": 3_000,
        "learning_rate": 0.05,
        "max_depth": 5,
        #"colsample_bylevel": 0.1,
       
    }
# print out training values 10 times during training run
params["verbose"] = int(params["n_estimators"]/10)
    # max_leaves is left to default value of 31 as it recommended not to make it larger than 64
    
model = CatBoostRegressor(**params)

In [259]:
model.fit(X_train, y_train)

0:	learn: 0.2424571	total: 8.34ms	remaining: 25s
300:	learn: 0.0027889	total: 1.97s	remaining: 17.7s
600:	learn: 0.0000476	total: 3.91s	remaining: 15.6s
900:	learn: 0.0000009	total: 5.94s	remaining: 13.8s
1200:	learn: 0.0000000	total: 8.01s	remaining: 12s
1500:	learn: 0.0000000	total: 10s	remaining: 10s
1800:	learn: 0.0000000	total: 12.1s	remaining: 8.08s
2100:	learn: 0.0000000	total: 14.2s	remaining: 6.09s
2400:	learn: 0.0000000	total: 16.4s	remaining: 4.08s
2700:	learn: 0.0000000	total: 18.6s	remaining: 2.05s
2999:	learn: 0.0000000	total: 20.8s	remaining: 0us

In [260]:
feature_importances = model.get_feature_importance()

# Get feature names (assuming 'model.feature_names_' contains the feature names)
feature_names = model.feature_names_

# Combine feature names and importance scores into a DataFrame
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
})

# Sort the DataFrame by importance scores in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

In [261]:
top_100_feats=list(feature_importance_df["Feature"][:100])
top_200_feats=list(feature_importance_df["Feature"][:200])

In [262]:
X["MC1_FEAT"]=X.apply(lambda r: money(r["GCD_FEAT"]),axis=1)

In [263]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,MC1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,1,1,1,1,1,4,4,99,99,1
1,4,2,4,4,0,0,4,4,3,0,...,1,4,4,2,4,8,0,33,72,4
2,2,4,0,3,0,3,2,4,2,2,...,1,3,2,2,2,0,0,90,72,3
3,2,1,3,0,3,0,3,3,4,2,...,1,1,6,1,6,7,7,99,99,1
4,4,1,4,1,0,4,0,4,4,0,...,1,1,2,2,2,4,1,99,72,1

In [264]:
test=X
test=test[top_100_feats]
test

,feature_runtier_fetid_supplanter,feature_lamellicorn_undiscomfited_hoofer,feature_matchable_feminist_giacomo,feature_derogative_untendered_rectangle,feature_unpitying_polyatomic_theodicy,feature_winded_sylphish_northamptonshire,feature_unimpeded_saharan_arena,feature_whapping_liny_prelate,feature_cornier_gular_vespucci,feature_prepositional_disinclined_gettering,...,feature_unexcelled_chloric_curculio,feature_roiling_decorative_plowshare,feature_located_unifying_truant,feature_homiletic_lineate_bateleur,feature_hairlike_fantastic_prospect,feature_wavy_pearliest_triliteral,feature_subscribed_chilean_misaim,feature_mellowing_elative_purcell,feature_sentential_indentured_newspaper,feature_cinematographic_extroverted_hierogram
0,0,0,1,1,1,1,2,3,2,2,...,2,0,1,4,1,0,0,0,0,1
1,4,0,3,2,3,1,4,3,4,0,...,0,4,1,4,0,2,2,0,4,1
2,2,2,1,4,0,0,0,0,0,1,...,2,1,0,1,4,1,2,4,1,1
3,2,1,0,0,1,4,3,0,2,2,...,4,3,2,1,2,2,4,2,3,0
4,1,1,0,0,1,1,1,2,1,2,...,1,4,4,0,2,1,0,3,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,3,2,3,3,3,3,0,3,2,1,...,1,0,1,3,1,4,4,1,1,1
96,2,2,2,4,3,3,3,4,4,2,...,2,1,2,2,4,1,4,1,3,2
97,0,2,4,3,3,4,3,4,3,0,...,3,2,0,0,1,3,1,0,1,3
98,2,1,1,2,4,4,4,0,4,3,...,2,0,1,1,0,4,2,0,4,3
99,3,3,2,0,3,0,1,1,1,2,...,4,0,2,1,4,2,1,2,1,2

In [265]:
X["coladd100"]=X[top_100_feats].mod(2).sum(axis=1)

In [266]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,MC1_FEAT,coladd100
0,3,4,0,3,3,1,1,0,0,0,...,1,1,1,1,4,4,99,99,1,46
1,4,2,4,4,0,0,4,4,3,0,...,4,4,2,4,8,0,33,72,4,22
2,2,4,0,3,0,3,2,4,2,2,...,3,2,2,2,0,0,90,72,3,42
3,2,1,3,0,3,0,3,3,4,2,...,1,6,1,6,7,7,99,99,1,39
4,4,1,4,1,0,4,0,4,4,0,...,1,2,2,2,4,1,99,72,1,50

In [267]:
X["MC2_FEAT"]=X.apply(lambda r: money(r["coladd100"]),axis=1)

In [268]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,MC1_FEAT,coladd100,MC2_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,1,1,1,4,4,99,99,1,46,2
1,4,2,4,4,0,0,4,4,3,0,...,4,2,4,8,0,33,72,4,22,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,0,0,90,72,3,42,2
3,2,1,3,0,3,0,3,3,4,2,...,6,1,6,7,7,99,99,1,39,5
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,4,1,99,72,1,50,0

In [270]:
X["TOP_SUM"]=X[top_100_feats].apply(np.sum,axis=1)

In [271]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,MC1_FEAT,coladd100,MC2_FEAT,TOP_SUM
0,3,4,0,3,3,1,1,0,0,0,...,1,1,4,4,99,99,1,46,2,170
1,4,2,4,4,0,0,4,4,3,0,...,2,4,8,0,33,72,4,22,2,290
2,2,4,0,3,0,3,2,4,2,2,...,2,2,0,0,90,72,3,42,2,250
3,2,1,3,0,3,0,3,3,4,2,...,1,6,7,7,99,99,1,39,5,207
4,4,1,4,1,0,4,0,4,4,0,...,2,2,4,1,99,72,1,50,0,198

In [272]:
X["MC3_FEAT"]=X.apply(lambda r: money(r["TOP_SUM"]),axis=1)

In [273]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,MC1_FEAT,coladd100,MC2_FEAT,TOP_SUM,MC3_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,1,4,4,99,99,1,46,2,170,0
1,4,2,4,4,0,0,4,4,3,0,...,4,8,0,33,72,4,22,2,290,0
2,2,4,0,3,0,3,2,4,2,2,...,2,0,0,90,72,3,42,2,250,0
3,2,1,3,0,3,0,3,3,4,2,...,6,7,7,99,99,1,39,5,207,3
4,4,1,4,1,0,4,0,4,4,0,...,2,4,1,99,72,1,50,0,198,4