In [1]:
from pathlib import Path
import pandas as pd
import  gc 
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
import catboost
from catboost import datasets, CatBoostRegressor

In [2]:
p = Path.home() / 'AppData' / 'Local' / 'Packages' / \
...     'PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0' / \
...     'LocalCache' / 'local-packages' / 'Python39' / 'Scripts' / 'sample_train_numerai.csv'

train = pd.read_csv(p)

In [3]:
y=train["target"]
X=train.drop("target",axis=1)
X

,era,data_type,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,1,train,3,4,0,3,3,1,1,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,1,train,4,2,4,4,0,0,4,4,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,1,train,2,4,0,3,0,3,2,4,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,1,train,2,1,3,0,3,0,3,3,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,1,train,4,1,4,1,0,4,0,4,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,train,0,1,4,0,3,2,3,2,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,1,train,2,3,3,0,3,0,1,0,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,1,train,3,1,1,0,0,1,0,3,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,1,train,2,0,2,1,4,1,2,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,1,train,3,4,2,2,0,4,3,4,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [4]:
X=X.drop("era",axis=1)
X=X.drop("data_type",axis=1)
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,3,4,0,3,3,1,1,0,0,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,4,2,4,4,0,0,4,4,3,0,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,2,4,0,3,0,3,2,4,2,2,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,2,1,3,0,3,0,3,3,4,2,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,4,1,4,1,0,4,0,4,4,0,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,2,3,3,0,3,0,1,0,2,3,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,3,1,1,0,0,1,0,3,1,2,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,2,0,2,1,4,1,2,2,1,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,3,4,2,2,0,4,3,4,2,3,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [5]:
good_cols=[col for col in X.columns if not col.startswith("target")]
 
X=X[good_cols]
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_sprucer_godlier_assembling,feature_venturesome_jesting_characterisation,feature_unstained_anhedonic_hetty,feature_vivisectional_latvian_dispensator,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,2,2,2,2
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,2,2,2,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,2,2,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,2,2,2,2
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,2,2,2,2,2,2,2,2,2,2
96,2,3,3,0,3,0,1,0,2,3,...,2,2,2,2,2,2,2,2,2,2
97,3,1,1,0,0,1,0,3,1,2,...,2,2,2,2,2,2,2,2,2,2
98,2,0,2,1,4,1,2,2,1,2,...,2,2,2,2,2,2,2,2,2,2
99,3,4,2,2,0,4,3,4,2,3,...,2,2,2,2,2,2,2,2,2,2

In [6]:
X=X.reset_index(drop=True)
y=y.reset_index(drop=True)

In [7]:
X.isnull().values.any()

np.False_

In [8]:
def  kin_energy(x):
    f=np.unique(x,return_counts=True)
    prob=f[1]/x.shape[0]
    energy=np.sum(prob**2)
    return  energy

In [9]:
def count_common(x):
    a=np.array(x)
    b=np.where(a==np.min(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [10]:
def count_least(x):
    a=np.array(x)
    b=np.where(a==np.max(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [11]:
X["KINETIC_FEAT"]=X.apply(kin_energy,axis=1)
X["mean_FEAT"]=X[good_cols].apply(np.mean,axis=1)
X["COMMON_COUNT_FEAT"]=X.apply(count_common,axis=1)
X["LEAST_COUNT_FEAT"]=X.apply(count_least,axis=1)

In [12]:
del train
gc.collect()

0

In [13]:
X["KINETIC_FEAT"]=np.round(X["KINETIC_FEAT"], decimals=2)
X["mean_FEAT"]=np.round(X["mean_FEAT"], decimals=2)

In [14]:
X["KINETIC_FEAT"]=( X["KINETIC_FEAT"]% 1 * 100).astype(int)
X["mean_FEAT"]=( X["mean_FEAT"]% 1 * 100).astype(int)

In [15]:
train=X

In [16]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,40,0,182,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,39,95,400,1
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,43,96,167,1
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,40,0,203,1
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,38,2,221,1

In [17]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [18]:
params = {
        "n_estimators": 3_000,
        "learning_rate": 0.05,
        "max_depth": 5,
        #"colsample_bylevel": 0.1,
       
    }
# print out training values 10 times during training run
params["verbose"] = int(params["n_estimators"]/10)
    # max_leaves is left to default value of 31 as it recommended not to make it larger than 64
    
model = CatBoostRegressor(**params)

In [19]:
model.fit(X_train, y_train)

0:	learn: 0.2423633	total: 205ms	remaining: 10m 14s
300:	learn: 0.0028510	total: 7.83s	remaining: 1m 10s
600:	learn: 0.0000401	total: 15.5s	remaining: 1m 2s
900:	learn: 0.0000009	total: 23.2s	remaining: 54.1s
1200:	learn: 0.0000000	total: 30.7s	remaining: 46s
1500:	learn: 0.0000000	total: 38.2s	remaining: 38.2s
1800:	learn: 0.0000000	total: 45.9s	remaining: 30.5s
2100:	learn: 0.0000000	total: 53.5s	remaining: 22.9s
2400:	learn: 0.0000000	total: 1m 1s	remaining: 15.3s
2700:	learn: 0.0000000	total: 1m 8s	remaining: 7.62s
2999:	learn: 0.0000000	total: 1m 16s	remaining: 0us

In [20]:
feature_importances = model.get_feature_importance()

# Get feature names (assuming 'model.feature_names_' contains the feature names)
feature_names = model.feature_names_

# Combine feature names and importance scores into a DataFrame
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
})

# Sort the DataFrame by importance scores in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

In [21]:
feature_importances

array([3.80522744e-09, 4.67340200e-02, 2.49639225e-19, ...,
       1.19433755e-01, 1.96913572e-01, 0.00000000e+00])

In [22]:
np.corrcoef(X["feature_elusive_vapoury_accomplice"], X["feature_approbatory_labroid_coracle"])

array([[ 1.        , -0.06994773],
       [-0.06994773,  1.        ]])

In [23]:
def gcd(a, b):
    if a == 0 or b == 0:
        return max(a, b)
    return gcd(b, a % b)

In [24]:
X["GCD_FEAT"]=X.apply(lambda r: gcd(r["feature_elusive_vapoury_accomplice"],r["feature_fortified_repressed_baird"]),axis=1)

In [25]:
def l(a, b):
    if a==0 or b==0:
        return max(a, b)
    else:
        if a!=0 and b!=0:
           lcm=(a*b)/gcd(a, b)
    if a==0 and b==0:
        return 0
    return lcm

In [26]:
X["LCM_FEAT"]=X.apply(lambda r: l(r["feature_elusive_vapoury_accomplice"], r["feature_limiest_heliolithic_york"]),axis=1)

In [27]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,40,0,182,1,1,1.0
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,39,95,400,1,4,4.0
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,43,96,167,1,3,2.0
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,40,0,203,1,1,6.0
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,38,2,221,1,1,2.0

In [28]:
X["LCM_FEAT"]=X["LCM_FEAT"].astype(int)

In [29]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,40,0,182,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,39,95,400,1,4,4
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,43,96,167,1,3,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,40,0,203,1,1,6
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,38,2,221,1,1,2

In [30]:
def sum_q(l, r, x):
    a=np.array(x)
    n=len(a)
    if l>r:
        aux=l
        l=r
        r=aux
    if r==l:
        s=a[0]
    if n>r and  n>l:
            s=sum(a[i] for i in range(l, r))
  
            return s

In [31]:
x=[1, -1, 7, 2, -3, -2, 4]
print (sum_q(1, 4, x))
print (sum_q(2, 6, x))

8
4

In [32]:
np.corrcoef(X["GCD_FEAT"], X["LCM_FEAT"])

array([[1.        , 0.17254718],
       [0.17254718, 1.        ]])

In [33]:
X["SUM_QUERY_FEAT"]=X.apply(lambda r: sum_q(r["GCD_FEAT"], r["LCM_FEAT"], r),axis=1)

In [34]:
train.head(20)

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,SUM_QUERY_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,40,0,182,1,1,1,0
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,39,95,400,1,4,4,0
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,43,96,167,1,3,2,0
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,40,0,203,1,1,6,7
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,38,2,221,1,1,2,1
5,4,2,2,3,0,4,1,4,1,3,...,2,2,2,45,85,308,1,1,0,4
6,1,3,1,2,1,4,1,1,3,3,...,2,2,2,44,16,108,1,4,4,0
7,4,4,4,4,0,0,4,2,3,0,...,2,2,2,37,94,287,1,3,3,0
8,3,1,3,0,1,1,2,4,1,0,...,2,2,2,39,84,407,1,2,2,0
9,0,3,0,3,4,4,1,1,0,2,...,2,2,2,40,6,202,1,3,3,0
10,4,0,0,4,4,0,0,0,2,0,...,2,2,2,38,77,452,1,1,4,4
11,0,2,3,1,4,0,4,4,0,1,...,2,2,2,41,90,282,1,2,2,0
12,4,0,1,0,2,4,2,4,3,2,...,2,2,2,39,86,290,1,1,1,0
13,1,1,1,2,3,0,0,1,4,3,...,2,2,2,44,98,186,1,1,3,2
14,1,0,1,0,4,0,4,1,2,2,...,2,2,2,42,98,190,1,1,3,1
15,0,4,3,4,2,1,4,2,0,2,...,2,2,2,38,25,152,1,1,3,7
16,4,2,4,2,2,3,1,0,4,2,...,2,2,2,42,89,340,1,2,4,6
17,2,3,0,1,1,0,2,4,1,3,...,2,2,2,41,0,131,1,2,4,1
18,4,1,4,4,2,4,4,1,3,4,...,2,2,2,43,8,189,1,3,12,22
19,0,0,2,3,4,1,0,0,3,4,...,2,2,2,42,16,130,1,1,4,5