In [315]:
from pathlib import Path
import pandas as pd
import  gc 
import numpy as np
from sklearn.model_selection import train_test_split
from catboost import CatBoostClassifier
import catboost
import lightgbm as lgb
from catboost import datasets, CatBoostRegressor

In [316]:
p = Path.home() / 'AppData' / 'Local' / 'Packages' / \
...     'PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0' / \
...     'LocalCache' / 'local-packages' / 'Python39' / 'Scripts' / 'sample_train_numerai.csv'

train = pd.read_csv(p)

In [317]:
y=train["target"]
X=train.drop("target",axis=1)
X

,era,data_type,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,1,train,3,4,0,3,3,1,1,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,1,train,4,2,4,4,0,0,4,4,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,1,train,2,4,0,3,0,3,2,4,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,1,train,2,1,3,0,3,0,3,3,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,1,train,4,1,4,1,0,4,0,4,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,1,train,0,1,4,0,3,2,3,2,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,1,train,2,3,3,0,3,0,1,0,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,1,train,3,1,1,0,0,1,0,3,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,1,train,2,0,2,1,4,1,2,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,1,train,3,4,2,2,0,4,3,4,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [318]:
X=X.drop("era",axis=1)
X=X.drop("data_type",axis=1)
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,target_teager2b_20,target_teager2b_60,target_tyler_20,target_tyler_60,target_victor_20,target_victor_60,target_waldo_20,target_waldo_60,target_xerxes_20,target_xerxes_60
0,3,4,0,3,3,1,1,0,0,0,...,0.50,0.50,0.25,0.25,0.25,0.25,0.25,0.00,0.25,0.00
1,4,2,4,4,0,0,4,4,3,0,...,0.50,0.50,0.25,0.25,0.25,0.00,0.25,0.25,0.25,0.25
2,2,4,0,3,0,3,2,4,2,2,...,1.00,1.00,1.00,0.75,0.75,0.75,0.75,1.00,0.75,0.75
3,2,1,3,0,3,0,3,3,4,2,...,0.25,0.25,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25
4,4,1,4,1,0,4,0,4,4,0,...,0.50,0.50,0.25,0.50,0.25,0.50,0.25,0.50,0.25,0.50
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,0.25,0.25,0.50,0.25,0.25,0.25,0.25,0.25,0.25,0.50
96,2,3,3,0,3,0,1,0,2,3,...,0.50,0.25,0.50,0.50,0.50,0.50,0.50,0.25,0.50,0.50
97,3,1,1,0,0,1,0,3,1,2,...,0.25,0.75,0.25,0.50,0.25,0.50,0.00,0.75,0.25,0.75
98,2,0,2,1,4,1,2,2,1,2,...,0.50,0.75,0.50,0.50,0.25,0.25,0.50,0.50,0.50,0.75
99,3,4,2,2,0,4,3,4,2,3,...,0.50,0.50,0.25,0.00,0.50,0.50,0.25,0.25,0.25,0.50

In [319]:
good_cols=[col for col in X.columns if not col.startswith("target")]
 
X=X[good_cols]
X

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_sprucer_godlier_assembling,feature_venturesome_jesting_characterisation,feature_unstained_anhedonic_hetty,feature_vivisectional_latvian_dispensator,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,2,2,2,2
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,2,2,2,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,2,2,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,2,2,2,2
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,1,4,0,3,2,3,2,4,1,...,2,2,2,2,2,2,2,2,2,2
96,2,3,3,0,3,0,1,0,2,3,...,2,2,2,2,2,2,2,2,2,2
97,3,1,1,0,0,1,0,3,1,2,...,2,2,2,2,2,2,2,2,2,2
98,2,0,2,1,4,1,2,2,1,2,...,2,2,2,2,2,2,2,2,2,2
99,3,4,2,2,0,4,3,4,2,3,...,2,2,2,2,2,2,2,2,2,2

In [320]:
X=X.reset_index(drop=True)
y=y.reset_index(drop=True)

In [321]:
X.isnull().values.any()

np.False_

In [322]:
def  kin_energy(x):
    f=np.unique(x,return_counts=True)
    prob=f[1]/x.shape[0]
    energy=np.sum(prob**2)
    return  energy

In [323]:
def count_common(x):
    a=np.array(x)
    b=np.where(a==np.min(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [324]:
def count_least(x):
    a=np.array(x)
    b=np.where(a==np.max(a))
    v=np.array(b)
    nr_ap=v.shape[1]
    return nr_ap

In [325]:
X["KINETIC_FEAT"]=X.apply(kin_energy,axis=1)
X["mean_FEAT"]=X[good_cols].apply(np.mean,axis=1)
X["COMMON_COUNT_FEAT"]=X.apply(count_common,axis=1)
X["LEAST_COUNT_FEAT"]=X.apply(count_least,axis=1)

In [326]:
del train
gc.collect()

0

In [327]:
X["KINETIC_FEAT"]=np.round(X["KINETIC_FEAT"], decimals=2)
X["mean_FEAT"]=np.round(X["mean_FEAT"], decimals=2)

In [328]:
X["KINETIC_FEAT"]=( X["KINETIC_FEAT"]% 1 * 100).astype(int)
X["mean_FEAT"]=( X["mean_FEAT"]% 1 * 100).astype(int)

In [329]:
train=X

In [330]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pantheist_interramal_episcopalianism,feature_percurrent_deontic_sectionalisation,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,2,2,40,0,182,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,2,2,39,95,400,1
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,2,2,43,96,167,1
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,2,2,40,0,203,1
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,2,2,38,2,221,1

In [331]:
np.corrcoef(X["feature_elusive_vapoury_accomplice"], X["feature_approbatory_labroid_coracle"])

array([[ 1.        , -0.06994773],
       [-0.06994773,  1.        ]])

In [332]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [333]:
def gcd(a, b):
    if a == 0 or b == 0:
        return max(a, b)
    return gcd(b, a % b)

In [334]:
X["GCD_FEAT"]=X.apply(lambda r: gcd(r["feature_elusive_vapoury_accomplice"],r["feature_fortified_repressed_baird"]),axis=1)

In [335]:
def l(a, b):
    if a==0 or b==0:
        return max(a, b)
    else:
        if a!=0 and b!=0:
           lcm=(a*b)/gcd(a, b)
    if a==0 and b==0:
        return 0
    return lcm

In [336]:
X["LCM_FEAT"]=X.apply(lambda r: l(r["feature_elusive_vapoury_accomplice"], r["feature_limiest_heliolithic_york"]),axis=1)

In [337]:
X["LCM_FEAT"]=X["LCM_FEAT"].astype(int)

In [338]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_myalgic_eulogistic_propagation,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,2,40,0,182,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,2,39,95,400,1,4,4
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,2,43,96,167,1,3,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,2,40,0,203,1,1,6
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,2,38,2,221,1,1,2

In [339]:
def sum_q(l, r, x):
   
    a=np.array(x)
    n=len(a)
    if l>r:
        aux=l
        l=r
        r=aux
    if r==l:
        return a[r]
    if n>=r and  n>l:
            s=sum(a[i] for i in range(l, r))
  
            return s

In [340]:
x=[1, -1, 7, 2, -3, -2, 4]
print (sum_q(4, 4, x))
print (sum_q(2, 6, x))

-3
4

In [341]:
np.corrcoef(X["feature_busy_clear_divi"],X["feature_pococurante_typological_crump"])

C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_function_base_impl.py:2922: RuntimeWarning: invalid value encountered in divide
  c /= stddev[:, None]
C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_function_base_impl.py:2923: RuntimeWarning: invalid value encountered in divide
  c /= stddev[None, :]

array([[ 1., nan],
       [nan, nan]])

In [342]:
X["GCD1_FEAT"]=X.apply(lambda r: gcd(r["feature_busy_clear_divi"],r["feature_pococurante_typological_crump"]),axis=1)

In [343]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pressor_chiropodial_hypertension,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,2,40,0,182,1,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,2,39,95,400,1,4,4,2
2,2,4,0,3,0,3,2,4,2,2,...,2,2,2,43,96,167,1,3,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,2,40,0,203,1,1,6,1
4,4,1,4,1,0,4,0,4,4,0,...,2,2,2,38,2,221,1,1,2,2

In [344]:
np.corrcoef(X["feature_glandered_unimproved_peafowl"],X["feature_starving_unwet_transubstantiationalist"])

array([[1.      , 0.267411],
       [0.267411, 1.      ]])

In [345]:
X["LCM1_FEAT"]=X.apply(lambda r: l(r["feature_glandered_unimproved_peafowl"], r["feature_starving_unwet_transubstantiationalist"]),axis=1)

In [346]:
X["LCM1_FEAT"]=X["LCM_FEAT"].astype(int)

In [347]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_diogenic_wooden_lout,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,2,40,0,182,1,1,1,1,1
1,4,2,4,4,0,0,4,4,3,0,...,2,2,39,95,400,1,4,4,2,4
2,2,4,0,3,0,3,2,4,2,2,...,2,2,43,96,167,1,3,2,2,2
3,2,1,3,0,3,0,3,3,4,2,...,2,2,40,0,203,1,1,6,1,6
4,4,1,4,1,0,4,0,4,4,0,...,2,2,38,2,221,1,1,2,2,2

In [348]:
X["SUM_QUERY1_FEAT"]=X.apply(lambda r: sum_q(r["GCD1_FEAT"], r["LCM1_FEAT"], r),axis=1)

In [349]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,feature_pleuritic_equipotent_loudmouth,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,2,40,0,182,1,1,1,1,1,4
1,4,2,4,4,0,0,4,4,3,0,...,2,39,95,400,1,4,4,2,4,8
2,2,4,0,3,0,3,2,4,2,2,...,2,43,96,167,1,3,2,2,2,0
3,2,1,3,0,3,0,3,3,4,2,...,2,40,0,203,1,1,6,1,6,7
4,4,1,4,1,0,4,0,4,4,0,...,2,38,2,221,1,1,2,2,2,4

In [350]:
X["SUM_QUERY_FEAT"]=X.apply(lambda r: sum_q(r["GCD_FEAT"], r["LCM_FEAT"], r),axis=1)

In [351]:
train.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,KINETIC_FEAT,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,40,0,182,1,1,1,1,1,4,4
1,4,2,4,4,0,0,4,4,3,0,...,39,95,400,1,4,4,2,4,8,0
2,2,4,0,3,0,3,2,4,2,2,...,43,96,167,1,3,2,2,2,0,0
3,2,1,3,0,3,0,3,3,4,2,...,40,0,203,1,1,6,1,6,7,7
4,4,1,4,1,0,4,0,4,4,0,...,38,2,221,1,1,2,2,2,4,1

In [352]:
def josephus(n, k):
   
    if n==1: 
        return 0
    else:
        
        return  (josephus(n - 1, k) + k) % n

In [353]:
X["JOSE_FEAT"]=X.apply(lambda r: josephus(100, r["GCD_FEAT"]),axis=1)

In [354]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,mean_FEAT,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,0,182,1,1,1,1,1,4,4,99
1,4,2,4,4,0,0,4,4,3,0,...,95,400,1,4,4,2,4,8,0,33
2,2,4,0,3,0,3,2,4,2,2,...,96,167,1,3,2,2,2,0,0,90
3,2,1,3,0,3,0,3,3,4,2,...,0,203,1,1,6,1,6,7,7,99
4,4,1,4,1,0,4,0,4,4,0,...,2,221,1,1,2,2,2,4,1,99

In [355]:
X["JOSE1_FEAT"]=X.apply(lambda r: josephus(100, r["GCD1_FEAT"]),axis=1)

In [356]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,COMMON_COUNT_FEAT,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,182,1,1,1,1,1,4,4,99,99
1,4,2,4,4,0,0,4,4,3,0,...,400,1,4,4,2,4,8,0,33,72
2,2,4,0,3,0,3,2,4,2,2,...,167,1,3,2,2,2,0,0,90,72
3,2,1,3,0,3,0,3,3,4,2,...,203,1,1,6,1,6,7,7,99,99
4,4,1,4,1,0,4,0,4,4,0,...,221,1,1,2,2,2,4,1,99,72

In [357]:

def entropy(x, b):
    a=np.array(x)
    prob=a[1]/a.shape[0]
    D=np.emath.logn(b, prob) 
    entropy=-np.sum(prob*D)
    return entropy

In [358]:
X["ENTROPY_FEAT"]=X.apply(lambda r: entropy(r, 2),axis=1)

C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_scimath_impl.py:386: RuntimeWarning: divide by zero encountered in log
  return nx.log(x)/nx.log(n)
C:\Users\Asus\AppData\Local\Temp\ipykernel_31360\1187988177.py:5: RuntimeWarning: invalid value encountered in scalar multiply
  entropy=-np.sum(prob*D)

In [360]:
X.head()

,feature_shaded_hallucinatory_dactylology,feature_itinerant_hexahedral_photoengraver,feature_prudent_pileate_oven,feature_subalpine_apothegmatical_ajax,feature_pistachio_atypical_malison,feature_symmetrical_spongy_tricentenary,feature_ungrounded_transpontine_winder,feature_aseptic_eely_hemiplegia,feature_elemental_easier_alkalinity,feature_cycloid_zymotic_galloway,...,LEAST_COUNT_FEAT,GCD_FEAT,LCM_FEAT,GCD1_FEAT,LCM1_FEAT,SUM_QUERY1_FEAT,SUM_QUERY_FEAT,JOSE_FEAT,JOSE1_FEAT,ENTROPY_FEAT
0,3,4,0,3,3,1,1,0,0,0,...,1,1,1,1,1,4,4,99,99,0.015447
1,4,2,4,4,0,0,4,4,3,0,...,1,4,4,2,4,8,0,33,72,0.008561
2,2,4,0,3,0,3,2,4,2,2,...,1,3,2,2,2,0,0,90,72,0.015447
3,2,1,3,0,3,0,3,3,4,2,...,1,1,6,1,6,7,7,99,99,0.004699
4,4,1,4,1,0,4,0,4,4,0,...,1,1,2,2,2,4,1,99,72,0.004699

In [361]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.25, random_state=42)

In [362]:
params = {
        "n_estimators": 3_000,
        "learning_rate": 0.05,
        "max_depth": 5,
        #"colsample_bylevel": 0.1,
       
    }
# print out training values 10 times during training run
params["verbose"] = int(params["n_estimators"]/10)
    # max_leaves is left to default value of 31 as it recommended not to make it larger than 64
    
model = CatBoostRegressor(**params)

In [363]:
model.fit(X_train, y_train)

0:	learn: 0.2420543	total: 8.79ms	remaining: 26.4s
300:	learn: 0.0026669	total: 1.94s	remaining: 17.4s
600:	learn: 0.0000202	total: 3.88s	remaining: 15.5s
900:	learn: 0.0000003	total: 5.8s	remaining: 13.5s
1200:	learn: 0.0000000	total: 7.89s	remaining: 11.8s
1500:	learn: 0.0000000	total: 9.86s	remaining: 9.84s
1800:	learn: 0.0000000	total: 11.9s	remaining: 7.91s
2100:	learn: 0.0000000	total: 13.9s	remaining: 5.96s
2400:	learn: 0.0000000	total: 16s	remaining: 4s
2700:	learn: 0.0000000	total: 18.2s	remaining: 2.01s
2999:	learn: 0.0000000	total: 20.3s	remaining: 0us

In [364]:
feature_importances = model.get_feature_importance()

# Get feature names (assuming 'model.feature_names_' contains the feature names)
feature_names = model.feature_names_

# Combine feature names and importance scores into a DataFrame
feature_importance_df = pd.DataFrame({
    'Feature': feature_names,
    'Importance': feature_importances
})

# Sort the DataFrame by importance scores in descending order
feature_importance_df = feature_importance_df.sort_values(by='Importance', ascending=False)

In [365]:
feature_importance_df.to_csv('Importance_cat_boost.csv',index=False)

In [373]:
top_200_feats=list(feature_importance_df["Feature"][:200])

In [375]:
top_200_feats

['feature_unimpeded_saharan_arena',
 'feature_matchable_feminist_giacomo',
 'feature_proto_rachidial_heldentenor',
 'feature_sentential_indentured_newspaper',
 'feature_wrongful_oriented_action',
 'feature_zymolytic_intertidal_privet',
 'feature_dicastic_unrepelled_propulsion',
 'feature_unformed_bent_smatch',
 'feature_untuneable_congealed_matterhorn',
 'feature_filagree_redundant_underestimation',
 'feature_critical_changeful_porgy',
 'feature_lacklustre_centroidal_schweitzer',
 'feature_intertentacular_xenophobic_leibnitzianism',
 'feature_runtier_fetid_supplanter',
 'feature_unworking_seismological_intervenient',
 'feature_prepositional_disinclined_gettering',
 'feature_biserial_formed_mendacity',
 'feature_gory_unitarian_shellback',
 'feature_pyrochemical_unaccented_hamstring',
 'feature_reclaimed_insurrectional_moneyer',
 'feature_lamellicorn_undiscomfited_hoofer',
 'feature_princelier_overhead_teil',
 'feature_waterproofed_damfool_alerce',
 'feature_ailurophobic_boggy_trocar',
 'feature_bonapartean_biogenic_yodeller',
 'feature_mycological_rabelaisian_puking',
 'feature_scurrying_patelliform_genocide',
 'feature_ironic_bulging_lichgate',
 'feature_tough_hunted_muhammad',
 'feature_folkloric_judgemental_churinga',
 'feature_damascene_net_database',
 'feature_columnar_hierurgical_portrayal',
 'feature_fulgid_vaccinated_whitby',
 'feature_unmutilated_soaking_balibuntal',
 'feature_norse_oscine_salome',
 'feature_accosted_strengthened_displeasure',
 'feature_trigonometrical_emigrational_careen',
 'feature_reverberant_chippy_kisangani',
 'feature_sluggish_feral_wham',
 'feature_adorable_unsuitable_cholecystectomy',
 'feature_memnonian_stopped_boarder',
 'feature_unpledged_hastier_fragrancy',
 'feature_bivariate_rabid_fred',
 'feature_unfair_inculcative_trangam',
 'feature_active_yclept_hydrometallurgy',
 'feature_threadbare_booziest_shortie',
 'feature_slimmer_dippiest_reefer',
 'feature_chimeric_piscatorial_pantagruel',
 'feature_zippy_trine_diffraction',
 'feature_cream_morning_wexford',
 'feature_papal_waugh_telencephalon',
 'feature_graphological_halting_buroo',
 'feature_unproven_erotically_symbololatry',
 'feature_tenurial_perceptional_wilhelmshaven',
 'feature_trident_matutinal_acidimeter',
 'feature_factorial_magical_fjord',
 'feature_burmese_societal_rifling',
 'feature_pleasurable_facultative_benzol',
 'feature_perithecial_precise_glamour',
 'feature_unvitiated_drinking_scrimmager',
 'feature_bulbar_brachycephalic_sac',
 'feature_pistachio_atypical_malison',
 'feature_fascistic_necrotic_genip',
 'feature_mullioned_hidden_niece',
 'feature_winsome_decomposable_stemware',
 'feature_brummagem_freckliest_papaverine',
 'feature_winded_sylphish_northamptonshire',
 'feature_unwinnowed_omental_houseful',
 'feature_sunlit_untrampled_entoblast',
 'feature_pleural_interjectional_stilton',
 'feature_clausular_tribalism_ultracentrifuge',
 'feature_thrashing_bulky_orchidology',
 'feature_veriest_petrifying_synergy',
 'feature_unmatched_spluttering_syndication',
 'feature_clerkly_memoriter_crematory',
 'feature_turbinal_apothegmatical_phalansterian',
 'feature_blended_alexic_agent',
 'feature_lymphangial_lapidary_josephine',
 'feature_maoism_alienable_accompanier',
 'feature_advised_subdural_toadflax',
 'feature_diversified_feticidal_ousting',
 'feature_nae_inexistent_herniotomy',
 'feature_excommunicate_shier_convexity',
 'feature_multinational_unvocal_leather',
 'feature_himalayan_hypsometric_assignor',
 'feature_corporal_monophthongal_barricade',
 'feature_flamboyant_veterinary_expelling',
 'feature_radiosensitive_actable_radish',
 'feature_thumblike_impactive_nap',
 'feature_canicular_paronomastic_clubbed',
 'feature_traced_retrocessive_touchstone',
 'feature_eutherian_beastlier_bogong',
 'feature_hearted_slithery_grocery',
 'feature_mortified_muted_primer',
 'feature_aeneolithic_nineteenth_whipper',
 'feature_vulnerable_liked_lophobranchiate',
 'feature_quadrifid_reluctant_caen',
 'feature_botchy_unamusing_halachah',
 'feature_drowsing_perfect_sustainment',
 'feature_sourish_laniary_schlumbergera',
 'feature_phasic_esthonian_paladin',
 'feature_elemental_easier_alkalinity',
 'feature_micrometrical_perspectival_luffa',
 'feature_wearisome_pop_estrade',
 'feature_photographic_categorized_cowling',
 'feature_puggy_vindicated_gree',
 'feature_enrolled_breezy_petting',
 'feature_giocoso_trimestrial_bluegill',
 'feature_horsier_uncurtailed_whittle',
 'feature_adsorbed_rebuttable_imitator',
 'feature_grallatorial_minutely_rommany',
 'feature_substitutive_lacerated_souchong',
 'feature_chalkiest_lapidarian_rotunda',
 'feature_lowermost_strapped_riksdag',
 'feature_apperceptive_diphyodont_swingle',
 'feature_embryonal_ovine_anelace',
 'feature_froebelian_hallstatt_insensitivity',
 'feature_condensable_virulent_lazaretto',
 'feature_sapient_parliamentarian_monogamy',
 'feature_encroaching_coolish_rosalie',
 'feature_starving_unwet_transubstantiationalist',
 'feature_delitescent_idled_knothole',
 'feature_unrecognized_classical_metastable',
 'feature_agamid_yuletide_physiology',
 'feature_owlishly_remoter_forensicality',
 'feature_evolutive_incommutable_muffineer',
 'feature_chilly_unsanctified_instrumentalist',
 'feature_dietary_farfetched_bight',
 'feature_eleusinian_educible_impropriety',
 'feature_edwardian_isosteric_asthenia',
 'feature_reconditioned_underglaze_girasol',
 'feature_enduring_enwrapped_sahara',
 'feature_unpledged_zairean_corsican',
 'feature_trapped_antipapal_buffer',
 'feature_enhancive_nude_will',
 'feature_bottomed_dollish_systematization',
 'feature_deviant_philippian_ottrelite',
 'feature_caspian_separated_fatima',
 'feature_giddied_smooth_circumvallation',
 'feature_dumpy_funkiest_homestead',
 'feature_wesleyan_probeable_countermand',
 'feature_morish_mazy_queer',
 'feature_campanular_orbital_acyclovir',
 'feature_duskish_unsensitive_severity',
 'feature_conjunct_refined_plumule',
 'feature_cronk_outlying_individuation',
 'feature_afoul_drainable_cateran',
 'feature_threadbare_reviving_franco',
 'feature_inhibitory_embarrassing_nome',
 'feature_chasmogamic_interurban_ethmoid',
 'feature_labrid_judicatory_barbule',
 'feature_prescription_female_classification',
 'feature_renounceable_baking_stocker',
 'feature_verticillated_tenured_bosch',
 'feature_thick_snobbish_indiscretion',
 'feature_unremunerative_federalism_inexplicability',
 'feature_interlocking_unextended_infield',
 'LCM1_FEAT',
 'feature_trabecular_palindromical_cumbria',
 'feature_equitant_nattiest_burler',
 'feature_indirect_pluviometric_hyponymy',
 'feature_tempering_unreproached_flannelette',
 'feature_cornier_gular_vespucci',
 'feature_selachian_collembolan_devaluation',
 'feature_phytogeographic_preparatory_pussyfoot',
 'feature_cholinergic_crackbrained_calligrapher',
 'feature_miffier_brahminic_case',
 'feature_bloodiest_haematoid_mag',
 'feature_velate_abolitionary_definitude',
 'feature_phagedenic_eccentric_familiar',
 'feature_unpitying_polyatomic_theodicy',
 'feature_conglobate_scolopendrine_wordsworth',
 'feature_jewish_stained_disembowelment',
 'feature_scorpaenid_virile_austerlitz',
 'feature_unexcavated_tyrannicidal_procedure',
 'feature_kwa_decemviral_volatilisation',
 'feature_unguerdoned_pursuable_rozzer',
 'feature_veteran_philhellene_chantal',
 'feature_anionic_glottidean_heath',
 'feature_closer_sluttish_revealing',
 'feature_unreplenished_airtight_twitching',
 'feature_incomparable_corking_gallopade',
 'feature_divulsive_looniest_machtpolitik',
 'feature_decuple_lowse_lahore',
 'feature_saccharoid_parapeted_rigging',
 'feature_alternant_conferrable_fanfaron',
 'feature_frictional_glistening_otway',
 'mean_FEAT',
 'feature_lowered_fugitive_mudstone',
 'feature_frowsier_intercommunal_congolese',
 'feature_whapping_liny_prelate',
 'feature_implicated_perplexing_tangerine',
 'feature_fatalistic_brooding_fitzgerald',
 'feature_ubiquitarian_springy_sickener',
 'feature_equalized_fringy_heterospory',
 'feature_unsigned_canonist_robbie',
 'feature_regulating_aerobiotic_meliorator',
 'feature_vernacular_unprophetic_pandore',
 'feature_uncrystallisable_monkish_boracite',
 'feature_north_ranging_manubrium']

In [376]:
good_cols=top_200_feats
z=pd.DataFrame(X)

z=z[good_cols]
z

,feature_unimpeded_saharan_arena,feature_matchable_feminist_giacomo,feature_proto_rachidial_heldentenor,feature_sentential_indentured_newspaper,feature_wrongful_oriented_action,feature_zymolytic_intertidal_privet,feature_dicastic_unrepelled_propulsion,feature_unformed_bent_smatch,feature_untuneable_congealed_matterhorn,feature_filagree_redundant_underestimation,...,feature_whapping_liny_prelate,feature_implicated_perplexing_tangerine,feature_fatalistic_brooding_fitzgerald,feature_ubiquitarian_springy_sickener,feature_equalized_fringy_heterospory,feature_unsigned_canonist_robbie,feature_regulating_aerobiotic_meliorator,feature_vernacular_unprophetic_pandore,feature_uncrystallisable_monkish_boracite,feature_north_ranging_manubrium
0,2,1,3,0,4,0,1,0,2,4,...,3,2,1,4,1,1,0,2,1,0
1,4,3,3,4,0,0,3,0,4,4,...,3,4,2,0,3,1,0,4,0,4
2,0,1,0,1,0,2,2,1,2,1,...,0,4,2,3,2,3,4,2,3,4
3,3,0,2,3,0,2,3,2,3,4,...,0,2,0,2,4,4,1,3,4,2
4,1,0,1,0,3,1,4,0,0,4,...,2,4,0,1,0,4,0,0,3,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,0,3,4,1,4,2,0,2,2,1,...,3,1,4,2,2,2,4,2,4,2
96,3,2,3,3,3,2,0,2,1,0,...,4,3,2,3,0,2,3,1,3,0
97,3,4,4,1,4,3,1,3,2,2,...,4,1,3,1,1,0,3,1,4,3
98,4,1,4,4,3,1,0,0,4,1,...,0,1,3,4,1,3,1,4,2,2
99,1,2,3,1,2,3,0,3,2,2,...,1,2,2,2,2,2,1,2,0,4

In [377]:
z["ENTROPY1_FEAT"]=z.apply(lambda r: entropy(r, 2),axis=1)

C:\Users\Asus\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\LocalCache\local-packages\Python39\site-packages\numpy\lib\_scimath_impl.py:386: RuntimeWarning: divide by zero encountered in log
  return nx.log(x)/nx.log(n)
C:\Users\Asus\AppData\Local\Temp\ipykernel_31360\1187988177.py:5: RuntimeWarning: invalid value encountered in scalar multiply
  entropy=-np.sum(prob*D)

In [378]:
z.head(3)

,feature_unimpeded_saharan_arena,feature_matchable_feminist_giacomo,feature_proto_rachidial_heldentenor,feature_sentential_indentured_newspaper,feature_wrongful_oriented_action,feature_zymolytic_intertidal_privet,feature_dicastic_unrepelled_propulsion,feature_unformed_bent_smatch,feature_untuneable_congealed_matterhorn,feature_filagree_redundant_underestimation,...,feature_implicated_perplexing_tangerine,feature_fatalistic_brooding_fitzgerald,feature_ubiquitarian_springy_sickener,feature_equalized_fringy_heterospory,feature_unsigned_canonist_robbie,feature_regulating_aerobiotic_meliorator,feature_vernacular_unprophetic_pandore,feature_uncrystallisable_monkish_boracite,feature_north_ranging_manubrium,ENTROPY1_FEAT
0,2,1,3,0,4,0,1,0,2,4,...,2,1,4,1,1,0,2,1,0,0.038219
1,4,3,3,4,0,0,3,0,4,4,...,4,2,0,3,1,0,4,0,4,0.090883
2,0,1,0,1,0,2,2,1,2,1,...,4,2,3,2,3,4,2,3,4,0.038219